import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../componenets/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Gist 🚀</title>
        <meta name="description" content="Generated by Touhidul Islam Chayan" />
        <link rel="icon" href="/C.G.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://chnspart.com">Next.js! 🚀</a>
        </h1>

        <p className={styles.description}>
          Written by{' '}
          <code className={styles.code}>CHNsPart</code>
        </p>

        <div className={styles.grid}>
          
          <a
            href="#"
            className={styles.card}
          >
            <h2>Card One &rarr;</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus voluptatem quos fugiat. </p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Card Two &rarr;</h2>
            <p>
              Tenetur officiis temporibus quo ipsum atque non possimus iure consectetur iste mollitia molestias.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
        >
          Powered by{' '}
          <span style={{marginLeft:"10px"}}>
            <Image src="/C.G.png" alt="CHNsPart Logo" width={30} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}
